### ISSUE TITLE
[BUG] There are not being mapping all available fields from a _cat/indices response

### ISSUE THREAD

**Issue by leonardomoralopez89** [opensearch-project/opensearch-java#286] opened 2022-12-02 14:59 UTC
### What is the bug?
When I try to get index information like `client.cat().indices()` in the response, I see the default fields, but for example, the index creation date is not coming up.
If I request elastic directly, I get the response with the index creation date, so the value is there; why are you not mapping it?
Is there any way to do that?

### How can one reproduce the bug?

1. Configure your client
2. Create a request for `client.cat().indices().valueBody()`
3. Check the response and you will see that the index creation date is not coming up

### What is the expected behavior?
That the values of all the available fields come in the response to a cat/indices request

### What is your host/environment?
I'm using the docker images of the opensearch (2.4.0) in a machine with Windows 11

### Do you have any screenshots?
1. Example request by using the opensearch java client

![image](https://user-images.githubusercontent.com/41559395/205319543-e6cfa1ed-eca3-48ca-bc6a-c5e5ec6385c5.png)

2. As you can see, there is no any index creation date available

![image](https://user-images.githubusercontent.com/41559395/205320901-df2be0f0-03e3-47e8-acab-8c30f0c7b413.png)

4. Making the request directly to elastic using DSL

![image](https://user-images.githubusercontent.com/41559395/205321394-bfd37c86-4589-4c4a-97cc-bd2a1569e9d1.png)

5. Here are the response

![image](https://user-images.githubusercontent.com/41559395/205321604-552cadb3-2ace-440a-bbd4-c3188bc86831.png)

**Comment by wbeckler** [comment] 2022-12-06 17:25
This looks like a genuine bug, with possibly a mismatch between the client expectations and the API version. Feel free to propose a PR for this.

**Comment by leonardomoralopez89** [comment] 2022-12-09 12:16
So, you are not supporting this client implementation anymore; you stop implementing new functionalities or fixing current bugs for this project???

**Comment by dblock** [comment] 2022-12-16 21:12
@leonardomoralopez89 We are supporting and fixing, as fast as we can. We are also trying to focus more energy on building automation for generating this and other clients from spec so we can be always up-to-date. And since this is open-source you can help, too, and get your fix much faster!

**Comment by VachaShah** [comment] 2023-09-15 02:03
Hi @leonardomoralopez89, to get the `creationDate` in the response, it has to be specified in the headers of the cat indices request like how you would do when sending a request directly. 

With just `client.cat().indices().valueBody()`, the client calls the /_cat/indices which returns the default fields in the result specified in https://opensearch.org/docs/latest/api-reference/cat/cat-indices/. To get additional fields in the response, you can specify the fields in the headers as follows:

```
List<IndicesRecord> indicesRecords = client.cat().indices(r -> r.headers("index,health,status,uuid,pri,rep,docs.count," +
                "docs.deleted,store.size,pri.store.size,creation.date,creation.date.string").bytes(Bytes.Bytes)).valueBody();

for (IndicesRecord record : indicesRecords) {
    System.out.println(record.index());
    System.out.println(record.health());
    System.out.println(record.status());
    System.out.println(record.docsCount());
    System.out.println(record.docsDeleted());
    System.out.println(record.storeSize());
    System.out.println(record.creationDate());
    System.out.println(record.creationDateString());
    System.out.println(record.uuid());
    System.out.println(record.priStoreSize());
}
```

This gives the creationDate in milliseconds and creationDateString in string. Snippet:

```
Creation date: 1694743007983
Creation date string: 2023-09-15T01:56:47.983Z
```

I will add this sample in the https://github.com/opensearch-project/opensearch-java/tree/main/samples as well.

**Comment by VachaShah** [comment] 2023-09-15 02:09
Closing this issue since its not a bug and documentation is now updated to reflect the correct usage. Please feel free to reopen if there are any more issues. Thank you!

**Closed by VachaShah** 2023-09-15 02:09 UTC
Labels: documentation
