### ISSUE TITLE
[BUG] org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'OpenSearchVersionInfo.distribution'

### ISSUE THREAD

**Issue by jhg023** [opensearch-project/opensearch-java#573] opened 2023-07-09 06:54 UTC
### What is the bug?
Earlier today, I upgraded my AWS OpenSearch cluster from version 2.5 to 2.7, and now I'm seeing the following exception when fetching the cluster information on startup:
```java
Caused by: org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'OpenSearchVersionInfo.distribution'
    at org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:88) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.opensearch._types.OpenSearchVersionInfo.<init>(OpenSearchVersionInfo.java:82) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.opensearch._types.OpenSearchVersionInfo$Builder.build(OpenSearchVersionInfo.java:324) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.opensearch._types.OpenSearchVersionInfo$Builder.build(OpenSearchVersionInfo.java:214) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:93) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:85) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:189) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:150) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:92) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.transport.aws.AwsSdk2Transport.parseResponse(AwsSdk2Transport.java:522) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.transport.aws.AwsSdk2Transport.executeSync(AwsSdk2Transport.java:393) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:191) ~[opensearch-java-2.6.0.jar!/:na]
    at org.opensearch.client.opensearch.OpenSearchClient.info(OpenSearchClient.java:860) ~[opensearch-java-2.6.0.jar!/:na]
```

### How can one reproduce the bug?
1. Create an AWS OpenSearch domain running version 2.7 (the latest version AWS supports currently).
2. Create your `OpenSearchClient`:
```java
var client = new OpenSearchClient(
    new AwsSdk2Transport(
        ApacheHttpClient.builder().build(),
        opensearchHost,
        "es",
        Region.US_WEST_2,
        AwsSdk2TransportOptions.builder().build()
    )
);
```
3. Attempt to fetch information on the cluster:
```java
var clusterName = client.info().clusterName();
```

### What is the expected behavior?
I wouldn't expect this to result in an exception, but rather print the cluster information even if the distribution is missing.

### What is your host/environment?
AWS OpenSearch 2.7 (the latest version AWS supports currently)

### Do you have any screenshots?
N/A

### Do you have any additional context?
If the fix for this issue is as simple as refactoring the following line, I'd be happy to PR it:
```java
this.distribution = ApiTypeHelper.requireNonNull(builder.distribution, this, "distribution");
```
For now, I'm going to avoid fetching the cluster information on startup as a temporary solution.

**Comment by wbeckler** [comment] 2023-07-10 02:06
What version of the java client are you using?

**Comment by jhg023** [comment] 2023-07-10 02:07
Using version `2.6.0` of `opensearch-java`

**Comment by reta** [comment] 2023-08-07 13:22
@jhg023 @wbeckler  the `distribution` is a required property returned by the OpenSearch server, the issue looks to be AWS specific. The server/client API model is correct.

**Comment by jhg023** [comment] 2023-08-07 14:44
In that case, I can open a support ticket to AWS to investigate.

**Comment by dblock** [comment] 2023-08-07 20:39
I created a 2.7 domain and I cannot reproduce this, I see *distribution* below. What do you see @jhg023?

```
$ awscurl --region=us-west-2 --service es https://search-dblock-test-opensearch-27-....us-west-2.es.amazonaws.com 
{
  "name" : "fcecc570a4b1e0527475991424f81e8d",
  "cluster_name" : "013306242651:dblock-test-opensearch-27",
  "cluster_uuid" : "CDx1PKXnQnuym3oTrEPglA",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.7.0",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2023-06-28T07:07:20.444435752Z",
    "build_snapshot" : false,
    "lucene_version" : "9.5.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**Comment by jhg023** [comment] 2023-08-07 20:58
Unless AWS OpenSearch comes with that compatibility enabled by default, I never explicitly enabled it. Here's what I see using the same `awscurl` command:
```
{
  "name" : "50101469e0d4fa***caca4915",
  "cluster_name" : "924108133664:***-prod",
  "cluster_uuid" : "***-OZnA",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2023-07-04T04:44:03.664641392Z",
    "build_snapshot" : false,
    "lucene_version" : "9.5.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```
Seeing as how the `number` field in my response has a value of `7.10.2`, I suspect there's some ES 7.10 compatibility happening here.

**Comment by dblock** [comment] 2023-08-07 21:07
@jhg023 So yes, this is compatibility mode. When you create a new domain there's a checkbox to enable/disable it. If you don't need this, you can toggle it via API 

```
$ awscurl --region=us-west-2 --service es https://search-dblock-test-opensearch-27-...us-west-2.es.amazonaws.com 
{
  "name" : "fcecc570a4b1e0527475991424f81e8d",
  "cluster_name" : "013306242651:dblock-test-opensearch-27",
  "cluster_uuid" : "CDx1PKXnQnuym3oTrEPglA",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.7.0",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2023-06-28T07:07:20.444435752Z",
    "build_snapshot" : false,
    "lucene_version" : "9.5.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}

$ awscurl -X PUT  --region=us-west-2 --service es https://search-dblock-test-opensearch-27-...us-west-2.es.amazonaws.com/_cluster/settings -d'{"persistent":{"compatibility.override_main_response_version" : true}}' 
{"acknowledged":true,"persistent":{"compatibility":{"override_main_response_version":"true"}},"transient":{}}
osx ~/source/opensearch-project/project-tools/dblock-project-tools (main)$ awscurl --region=us-west-2 --service es https://search-dblock-test-opensearch-27-...us-west-2.es.amazonaws.com 
{
  "name" : "fcecc570a4b1e0527475991424f81e8d",
  "cluster_name" : "013306242651:dblock-test-opensearch-27",
  "cluster_uuid" : "CDx1PKXnQnuym3oTrEPglA",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2023-06-28T07:07:20.444435752Z",
    "build_snapshot" : false,
    "lucene_version" : "9.5.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

Shall we close this?

**Closed** 2023-08-07 21:08 UTC
Labels: bug

**Comment by andrross** [comment] 2023-08-07 21:12
> Unless AWS OpenSearch comes with that compatibility enabled by default, I never explicitly enabled it.

@jhg023 It's not the default, but there is a check box to enable compatibility mode on an Amazon OpenSearch Service domain when creating it via the console UI.

**Comment by jhg023** [comment] 2023-08-07 21:13
Thanks for letting me know! I created this domain through CloudFormation, so I suspect I may have unintentionally enabled it there, or didn't explicit opt to disable it.

**Comment by wbeckler** [comment] 2023-08-07 23:47
I don't get it. I thought the issue was that the server response was causing an exception. I don't think compatibility mode should cause an error.

**Comment by reta** [comment] 2023-08-08 00:08
> I don't get it. I thought the issue was that the server response was causing an exception. I don't think compatibility mode should cause an error.

The compatibility mode (which if I am not mistaken phased out in 3.0.0) is only need when it is desired that OpenSearch cluster could be accessed by Elasticsearch clients (not OpenSearch clients).

**Comment by andrross** [comment] 2023-08-08 01:15
@reta The `compatibility.override_main_response_version` setting was actually removed in https://github.com/opensearch-project/OpenSearch/pull/3031 for the 2.0 release. However, Amazon OpenSearch Service has forward-ported this setting to the 2.x versions.

@wbeckler The question is whether opensearch-java should be compatible with OpenSearch running in a compatibility mode intended to make it compatible with Elasticsearch clients.

**Comment by dblock** [comment] 2023-08-08 15:06
> @wbeckler The question is whether opensearch-java should be compatible with OpenSearch running in a compatibility mode intended to make it compatible with Elasticsearch clients.

I believe the answer is no, there's no claims of opensearch-java working with Elasticsearch 7.10.

**Comment by wbeckler** [comment] 2023-08-09 09:49
Wouldn't it be better if the client could be cross compatible? Maybe with a
client compatibility mode flag as well?

**Comment by reta** [comment] 2023-08-09 11:52
> Wouldn't it be better if the client could be cross compatible?

We definitely shouldn't to take this route, the compatibility was interim measure, at this point the functionality between ES and OS diverged significantly, each has own ecosystem.

**Comment by amareshb** [comment] 2024-07-24 22:02
Faced the same issue today and had to set `compatibility.override_main_response_version` to false. 
```
PUT _cluster/settings
{
  "persistent": {
    "compatibility": {
      "override_main_response_version": false
    }
  }
}
```
This will add the property `"distribution" : "opensearch"` in the cluster info response. 

If you are running a managed version of opensearch like on AWS, you need to contact AWS support to update this setting.
